name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore MindfulDigger.sln

    - name: Build
      run: dotnet build MindfulDigger.sln --no-restore

    - name: Test
      run: dotnet test MindfulDigger.sln --no-build --verbosity normal

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Specify a Node.js version

    - name: Install npm dependencies
      run: npm ci

    - name: Build CSS
      run: npm run build:css
